version: 2

sources:
  - name: raw_data
    database: "{{ env_var('DBT_SNOWFLAKE_DATABASE') }}"
    schema: "{{ env_var('DBT_SNOWFLAKE_SCHEMA') }}"
    tables:
      - name: users
        identifier: raw_users
      - name: orders
        identifier: raw_orders
